version: "3.8"

services:
  media-service:
    build: .
    container_name: media-service
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      - .:/app
    networks:
      - media-net

networks:
  media-net:
    driver: bridge
